---
title: Activity 5 Results
format:
  html:
    code-fold: true
    code-summary: "See the code"
---

# Class Data Summary
```{r}
#| message: false
#| warning: false
# load tidyverse packages
library(tidyverse)

data <- read_csv("activities/06PenaltyKicks/EC327F24-activity6_results.csv") %>%
  filter(!is.na(s_k), !is.na(s_g)) # filter out missing data

N <- nrow(data)

# summarize by type of strategy profile
sum_stats <- data %>%
  group_by(s_k, s_g) %>% 
  summarise(
    n = n(), # get counts of each profile
    p = n / N, # calculate proportions
    num_goals = sum(goal), # count numbers of goals scored
    prob_goal = num_goals / N # probability of goal scored
  ) %>%
  unite(profile, c(s_k, s_g), sep = ":", remove = FALSE) 
sum_stats
```

## Plotting frequency of each strategy profile
```{r}
ggplot(sum_stats, aes(x = s_g, y = n, fill = s_k)) +
  geom_bar(stat = "identity") +
  facet_wrap(vars(s_k))
```

```{r}
# summarise win probabiltiy by kicker's strategy
kicker_strats <- data %>%
  group_by(s_k) %>%
  summarise(
    num_goals = sum(goal),
    prob_goal = sum(goal) / N
  )
kicker_strats
```

```{r}
# summarise win probabiltiy by goalie's strategy
goalie_strats <- data %>%
  group_by(s_k) %>%
  summarise(
    num_blocks = sum(goal == FALSE),
    prob_block = sum(goal == FALSE) / N
  )
goalie_strats

chisq.test(goalie_strats$num_blocks)
```

```{r}
# restrict to only Left and Right
data_LR <- data %>%
  filter(s_k %in% c("Left", "Right") & s_g %in% c("Left", "Right"))

N_LR <- nrow(data_LR)

sum_stats_LR <- data_LR %>%
  group_by(s_k, s_g) %>% # get counts of each profile
  summarise(
    n = n(),
    p = n / N,
    num_goals = sum(goal),
    prob_goal = num_goals / N
  )
sum_stats_LR

# Are data consistent w/ msne?
chisq.test(sum_stats_LR$n)
```
