---
title: "Homework Assignments"
---

# Assignment 1 [Download](01_Intro/main_clean.pdf){.btn .btn-outline-primary .btn role="button"}
**Due:** Friday, October 3rd
[**Submit to Canvas**](https://canvas.uoregon.edu/courses/274671/assignments/1922386){target="_blank"}
```{=html}
<details>
  <summary>Answer Key</summary>
  <div class="embed-container">
    <iframe src="01_Intro/HW1_key.pdf" style="border: 0.5px" height="1000" width="800"></iframe>
  </div>
</details>
```

# Assignment 2 [Download](02_Sequential/HW2_clean.pdf){.btn .btn-outline-primary .btn role="button"} 
**Due:** Friday, October 10th
[**Submit to Canvas**](https://canvas.uoregon.edu/courses/274671/assignments/1927365){target="_blank"}
```{=html}
<details>
  <summary>Answer Key</summary>
  <div class="embed-container">
    <iframe src="02_Sequential/HW2_key.pdf" style="border: 0.5px" height="1000" width="800"></iframe>
  </div>
</details>
```

# Assignment 3 [Download](03_Simultaneous/HW3_clean.pdf){.btn .btn-outline-primary .btn role="button"} 
**Due:** Friday, October 17th
[**Submit to Canvas**](https://canvas.uoregon.edu/courses/274671/assignments/1927367){target="_blank"}
```{=html}
<details>
  <summary>Answer Key</summary>
  <div class="embed-container">
    <iframe src="03_Simultaneous/HW3_key.pdf" style="border: 0.5px" height="1000" width="800"></iframe>
  </div>
</details>
```

# Assignment 4 [Download](04_Combined/HW4_clean.pdf){.btn .btn-outline-primary .btn role="button"} 
**Due:** Wednesday, October 29th
[**Submit to Canvas**](https://canvas.uoregon.edu/courses/274671/assignments/1927368){target="_blank"}
```{=html}
<details>
  <summary>Answer Key</summary>
  <div class="embed-container">
    <iframe src="04_Combined/HW4_key.pdf" style="border: 0.5px" height="1000" width="800"></iframe>
  </div>
</details>
```

# Assignment 5 [Download](05_Mixed/HW5_clean.pdf){.btn .btn-outline-primary .btn role="button"} 
**Due:** Monday, November 10th
[**Submit to Canvas**](https://canvas.uoregon.edu/courses/274671/assignments/1940611){target="_blank"}
```{=html}
<details>
  <summary>Answer Key</summary>
  <div class="embed-container">
    <iframe src="05_Mixed/HW5_key.pdf" style="border: 0.5px" height="1000" width="800"></iframe>
  </div>
</details>
```

# Assignment 6 [Download](06_Uncertainty/HW6_clean.pdf){.btn .btn-outline-primary .btn role="button"} 
**Due:** Wednesday, November 19th
[**Submit to Canvas**](https://canvas.uoregon.edu/courses/274671/assignments/1943344){target="_blank"}
```{=html}
<details>
  <summary>Expand</summary>
  <div class="embed-container">
    <iframe src="06_Uncertainty/HW6_clean.pdf" style="border: 0.5px" height="1000" width="800"></iframe>
  </div>
</details>
```

# Assignment 7 [Download](07_Evidence/HW7_clean.pdf){.btn .btn-outline-primary .btn role="button"} 
**Due:** Wednesday, November 26th
[**Submit to Canvas**](https://canvas.uoregon.edu/courses/274671/assignments/1943346){target="_blank"}
```{=html}
<details>
  <summary>Expand</summary>
  <div class="embed-container">
    <iframe src="07_Evidence/HW7_clean.pdf" style="border: 0.5px" height="1000" width="800"></iframe>
  </div>
</details>
```

# Assignment 8 [Download](08_Repeated/HW8_clean.pdf){.btn .btn-outline-primary .btn role="button"} 
**Due:** Friday, December 5th
[**Submit to Canvas**](https://canvas.uoregon.edu/courses/274671/assignments/1943347){target="_blank"}
```{=html}
<details>
  <summary>Expand</summary>
  <div class="embed-container">
    <iframe src="08_Repeated/HW8_clean.pdf" style="border: 0.5px" height="1000" width="800"></iframe>
  </div>
</details>
```