
## iClicker Poll}
```{=latex}
\begin{table}[h]
  \centering
  \begin{tabular}{cc|c|c|c|c|}
    & \multicolumn{1}{c}{} & \multicolumn{4}{c}{P$_2$}\\
    & \multicolumn{1}{c}{} & \multicolumn{1}{c}{$a$} & \multicolumn{1}{c}{$b$} & \multicolumn{1}{c}{$c$} & \multicolumn{1}{c}{$d$} \\\cline{3-6}
    \multirow{4}*{P$_1$}  & $A$ & 1, 0 & 2, 1 & 3, 1 & 4, 2 \\\cline{3-6}
    & $B$ & 3, 1 & 2, 2 & 2, 0 & 3, 0 \\\cline{3-6}
    & $C$ & 3, 1 & 4, 0 & 1, 0 & 2, 0 \\\cline{3-6}
    & $D$ & 4, 2 & 3, 0 & 2, 1 & 1, 1 \\\cline{3-6}
  \end{tabular}
\end{table}
```

::: {.incremental}
  * Suppose that you KNEW, without a doubt, that Player 2 would play $b$. If you were Player 1, what strategy would you choose?
    1. A
    1. B
    1. C
    1. D
    1. I would be indifferent between two or more strategies.
:::
---

## iClicker Poll}
```{=latex}
\begin{table}[h]
\centering
\begin{tabular}{cc|c|c|c|c|}
  & \multicolumn{1}{c}{} & \multicolumn{4}{c}{P$_2$}\\
  & \multicolumn{1}{c}{} & \multicolumn{1}{c}{$a$} & \multicolumn{1}{c}{$b$} & \multicolumn{1}{c}{$c$} & \multicolumn{1}{c}{$d$} \\\cline{3-6}
  \multirow{4}*{P$_1$}  & $A$ & 1, 0 & 2, 1 & 3, 1 & 4, 2 \\\cline{3-6}
  & $B$ & 3, 1 & 2, 2 & 2, 0 & 3, 0 \\\cline{3-6}
  & $C$ & 3, 1 & 4, 0 & 1, 0 & 2, 0 \\\cline{3-6}
  & $D$ & 4, 2 & 3, 0 & 2, 1 & 1, 1 \\\cline{3-6}
\end{tabular}
\end{table}
```
::: {.incremental}
* Suppose that you KNEW, without a doubt, that Player 1 would play $C$. If you were Player 2, what strategy would you choose?
  1. a
  1. b
  1. c
  1. d
  1. I would be indifferent between two or more strategies.
:::
---

## iClicker Poll}
```{=latex}
\begin{table}[h]
\centering
\begin{tabular}{cc|c|c|c|c|}
  & \multicolumn{1}{c}{} & \multicolumn{4}{c}{P$_2$}\\
  & \multicolumn{1}{c}{} & \multicolumn{1}{c}{$a$} & \multicolumn{1}{c}{$b$} & \multicolumn{1}{c}{$c$} & \multicolumn{1}{c}{$d$} \\\cline{3-6}
  \multirow{4}*{P$_1$}  & $A$ & 1, 0 & 2, 1 & 3, 1 & 4, 2 \\\cline{3-6}
  & $B$ & 3, 1 & 2, 2 & 2, 0 & 3, 0 \\\cline{3-6}
  & $C$ & 3, 1 & 4, 0 & 1, 0 & 2, 0 \\\cline{3-6}
  & $D$ & 4, 2 & 3, 0 & 2, 1 & 1, 1 \\\cline{3-6}
\end{tabular}
\end{table}
```
::: {.incremental}
* Suppose that you KNEW, without a doubt, that Player 2 would play $a$. If you were Player 1, what strategy would you choose?
  1. A
  1. B
  1. C
  1. D
  1. I would be indifferent between two or more strategies.
:::
---

## iClicker Poll}
```{=latex}
\begin{table}[h]
\centering
\begin{tabular}{cc|c|c|c|c|}
  & \multicolumn{1}{c}{} & \multicolumn{4}{c}{P$_2$}\\
  & \multicolumn{1}{c}{} & \multicolumn{1}{c}{$a$} & \multicolumn{1}{c}{$b$} & \multicolumn{1}{c}{$c$} & \multicolumn{1}{c}{$d$} \\\cline{3-6}
  \multirow{4}*{P$_1$}  & $A$ & 1, 0 & 2, 1 & 3, 1 & 4, 2 \\\cline{3-6}
  & $B$ & 3, 1 & 2, 2 & 2, 0 & 3, 0 \\\cline{3-6}
  & $C$ & 3, 1 & 4, 0 & 1, 0 & 2, 0 \\\cline{3-6}
  & $D$ & 4, 2 & 3, 0 & 2, 1 & 1, 1 \\\cline{3-6}
\end{tabular}
\end{table}
```
::: {.incremental}
* Suppose that you KNEW, without a doubt, that Player 1 would play $D$. If you were Player 2, what strategy would you choose?
  1. A
  1. B
  1. C
  1. D
  1. I would be indifferent between two or more strategies.
:::
---

## Best Responses}
::: {.incremental}
  * If you know what strategy the other player will choose, then you can easily figure out what your best option (or options) are.
  * Of course, you don't actually know what the other player will do when you choose your strategy in a game like this---but thinking about the game this way makes it easy to find NEs.
  * A strategy $s_i$ is a [best response]{.hi} to another player's strategy $s_{-i}$ if and only if it provides the highest payoff possible when the other player chooses $s_{-i}$.
:::
---

## Some Notes on Best Responses}
::: {.incremental}
  * The phrase "to another player's strategy" in the definition of a best response is **important**.
  * A strategy can only be a best response **to some strategy of the other player**. There is no such thing as a strategy which is just ``a best response."
  * When dealing with strategic-form games with game tables, there is always at least one best response to another player's strategy---and there may be multiple, if there is more than one strategy which provides the best payoff.
:::
---

## Best Responses in Practice}
::: {.incremental}
  * It's easy to depict best responses in a game table: we can go through each strategy in the game, and mark each strategy which is a best response to them.
  * We do this by marking the payoffs---however, it's important to understand that it's not the payoff itself which is a best response--we're just using them as a convenient way to depict where the best responses are.
    * In other words: don't try to describe the best response using the payoff. The best response is always the strategy.
:::
---

## Example: Best Responses in Game Table}
```{=latex}
\begin{table}[h]
  \centering
  \begin{tabular}{cc|c|c|c|c|}
    & \multicolumn{1}{c}{} & \multicolumn{4}{c}{P$_2$}\\
    & \multicolumn{1}{c}{} & \multicolumn{1}{c}{$a$} & \multicolumn{1}{c}{$b$} & \multicolumn{1}{c}{$c$} & \multicolumn{1}{c}{$d$} \\\cline{3-6}
    \multirow{4}*{P$_1$}  & $A$ & 1, 0 & 2, 1 & 3, 1 & 4, 2 \\\cline{3-6}
    & $B$ & 3, 1 & 2, 2 & 2, 0 & 3, 0 \\\cline{3-6}
    & $C$ & 3, 1 & 4, 0 & 1, 0 & 2, 0 \\\cline{3-6}
    & $D$ & 4, 2 & 3, 0 & 2, 1 & 1, 1 \\\cline{3-6}
  \end{tabular}
\end{table}
```
::: {.incremental}
  * To find Player 1's best responses, we will go through each column of the table (i.e. each of Player 2's strategies) and look for which of Player 1's strategies gives Player 1 the best payoff in that column.
:::
---

## Example: Best Responses in Game Table}
```{=latex}
\begin{table}[h]
\centering
\begin{tabular}{cc|c|c|c|c|}
  & \multicolumn{1}{c}{} & \multicolumn{4}{c}{P$_2$}\\
  & \multicolumn{1}{c}{} & \multicolumn{1}{c}{$a$} & \multicolumn{1}{c}{$b$} & \multicolumn{1}{c}{$c$} & \multicolumn{1}{c}{$d$} \\\cline{3-6}
  \multirow{4}*{P$_1$}  & $A$ & 1, 0 & 2, 1 & 3, 1 & 4, 2 \\\cline{3-6}
  & $B$ & 3, 1 & 2, 2 & 2, 0 & 3, 0 \\\cline{3-6}
  & $C$ & 3, 1 & 4, 0 & 1, 0 & 2, 0 \\\cline{3-6}
  & $D$ & 4, 2 & 3, 0 & 2, 1 & 1, 1 \\\cline{3-6}
\end{tabular}
\end{table}
```
::: {.incremental}
  * Likewise, to find Player 2's best responses, we will go through each **row** of the table (each of Player 1's strategies) and look for which of Player 2's strategies gives **Player 2** the best payoff in that column.
  ::: {.incremental}
    * The bolded parts are important: you have to look at Player 1's payoffs to find Player 1's best responses, and Player 2's payoffs to find Player 2's best responses.
  :::
:::
---

## Another Example: Best Responses in the Deer Hunt}
::: {.incremental}
  * Recall the Deer Hunt game, in which two cavemen each decide whether to hunt Deer or Rabbit.
  * We couldn't find a Nash Equilibrium to this game using elimination methods, because there was nothing to eliminate: no strategies are strictly dominated, and there are no strategies which are non-best-responses.
  * Here are Igg's best responses...
:::
```{=latex}
\begin{table}[h]
\centering
\begin{tabular}{cc|c|c|}
  & \multicolumn{1}{c}{} & \multicolumn{2}{c}{Ogg}\\
  & \multicolumn{1}{c}{} & \multicolumn{1}{c}{$Deer$}  & \multicolumn{1}{c}{$Rabbit$} \\\cline{3-4}
  \multirow{2}*{Igg}  & $Deer$ & $2,2$ & $0,1$ \\\cline{3-4}
  & $Rabbit$ & $1,0$ & $1,1$ \\\cline{3-4}
\end{tabular}
\end{table}
```
---

## Another Example: Best Responses in the Deer Hunt}
::: {.incremental}
  * And here are Ogg's best responses...
:::
```{=latex}
\begin{table}[h]
\centering
\begin{tabular}{cc|c|c|}
  & \multicolumn{1}{c}{} & \multicolumn{2}{c}{Ogg}\\
  & \multicolumn{1}{c}{} & \multicolumn{1}{c}{$Deer$}  & \multicolumn{1}{c}{$Rabbit$} \\\cline{3-4}
  \multirow{2}*{Igg}  & $Deer$ & $2,2$ & $0,1$ \\\cline{3-4}
  & $Rabbit$ & $1,0$ & $1,1$ \\\cline{3-4}
\end{tabular}
\end{table}
```
---

## Another Example: Non-Unique Best Responses}
::: {.incremental}
  * As mentioned earlier, best responses don't have to be unique.
:::
```{=latex}
\begin{table}[h]
\centering
\begin{tabular}{cc|c|c|}
  & \multicolumn{1}{c}{} & \multicolumn{2}{c}{Michael}\\
  & \multicolumn{1}{c}{} & \multicolumn{1}{c}{$Swerve$}  & \multicolumn{1}{c}{$Straight$} \\\cline{3-4}
  \multirow{2}*{Eleanor}  & $Swerve$ & $\underline{1}, 1$ & $\underline{1}, 1$ \\\cline{3-4}
  & $Straight$ & $\underline{1}, 1$ & $0, 0$ \\\cline{3-4}
\end{tabular}
\end{table}
```
::: {.incremental}
  * Here, for both players, both Straight and Swerve are best responses to Swerve. When the other player chooses Swerve, both strategies provide payoff of 1.
:::
---

## iClicker Q1}
```{=latex}
\begin{table}[h]
  \centering
  \begin{tabular}{cc|c|c|c|}
    & \multicolumn{1}{c}{} & \multicolumn{3}{c}{P$_2$}\\
    & \multicolumn{1}{c}{} & \multicolumn{1}{c}{$X$} & \multicolumn{1}{c}{$Y$} & \multicolumn{1}{c}{$Z$} \\\cline{3-5}
    \multirow{3}*{P$_1$}  & $A$ & 3, 3 & 2, 2 & 1, 1 \\\cline{3-5}
    & $B$ & 4, 2 & 1, 1 & 2, 2 \\\cline{3-5}
    & $C$ & 1, 1 & 2, 2 & 3, 1  \\\cline{3-5}
  \end{tabular}
\end{table}
```
::: {.incremental}
  * In the game shown above, what is Player 1's best response to X?
    1. A
    1. B
    1. C
    1. A and B are both best responses.
    1. A and C are both best responses.
:::
---

## iClicker Q2}
```{=latex}
\begin{table}[h]
\centering
\begin{tabular}{cc|c|c|c|}
  & \multicolumn{1}{c}{} & \multicolumn{3}{c}{P$_2$}\\
  & \multicolumn{1}{c}{} & \multicolumn{1}{c}{$X$} & \multicolumn{1}{c}{$Y$} & \multicolumn{1}{c}{$Z$} \\\cline{3-5}
  \multirow{3}*{P$_1$}  & $A$ & 3, 3 & 2, 2 & 1, 1 \\\cline{3-5}
  & $B$ & 4, 2 & 1, 1 & 2, 2 \\\cline{3-5}
  & $C$ & 1, 1 & 2, 2 & 3, 1  \\\cline{3-5}
\end{tabular}
\end{table}
```
::: {.incremental}
* In the game shown above, what is Player 1's best response to **Y**?
  1. A
  1. B
  1. C
  1. A and B are both best responses.
  1. A and C are both best responses.
:::
---

## iClicker Q3}
```{=latex}
\begin{table}[h]
\centering
\begin{tabular}{cc|c|c|c|}
  & \multicolumn{1}{c}{} & \multicolumn{3}{c}{P$_2$}\\
  & \multicolumn{1}{c}{} & \multicolumn{1}{c}{$X$} & \multicolumn{1}{c}{$Y$} & \multicolumn{1}{c}{$Z$} \\\cline{3-5}
  \multirow{3}*{P$_1$}  & $A$ & 3, 3 & 2, 2 & 1, 1 \\\cline{3-5}
  & $B$ & 4, 2 & 1, 1 & 2, 2 \\\cline{3-5}
  & $C$ & 1, 1 & 2, 2 & 3, 1  \\\cline{3-5}
\end{tabular}
\end{table}
```
::: {.incremental}
* In the game shown above, what is **Player 2's** best response to **C**?
  1. X
  1. Y
  1. Z
  1. X and Y are both best responses.
  1. X and Z are both best responses.
:::
---

## Nash Equilibrium from Best Responses}
::: {.incremental}
  * Recall the various definitions of a Nash Equilibrium:
    * a strategy profile such that no player can obtain a larger payoff by \textit{unilaterally deviating} (changing only their own strategy).
    * A strategy profile such that no single player can make themselves better off by changing only their own strategy.
    * A strategy profile such that, after the game is played, each player is satisfied that they could not have made a better decision.
  * Another definition we can use now is "A strategy profile such that each player's strategy is a best responses to the other player's strategy."
  * "Playing a best response" is equivalent to "cannot obtain a larger payoff by unilaterally deviating," or any of the other ways to describe this condition.
:::
---

## Nash Equilibrium from Best Responses}
::: {.incremental}
  * If we find each player's best responses in a game table, and do it using the same table for each player...
:::
```{=latex}
\begin{table}[h]
\centering
\begin{tabular}{cc|c|c|c|c|}
  & \multicolumn{1}{c}{} & \multicolumn{4}{c}{P$_2$}\\
  & \multicolumn{1}{c}{} & \multicolumn{1}{c}{$a$} & \multicolumn{1}{c}{$b$} & \multicolumn{1}{c}{$c$} & \multicolumn{1}{c}{$d$} \\\cline{3-6}
  \multirow{4}*{P$_1$}  & $A$ & 1, 0 & 2, 1 & \textbf{3}, 1 & \colorbox{blue!25}{\textbf{4}, \textbf{2}} \\\cline{3-6}
  & $B$ & 3, 1 & 2, \textbf{2} & 2, 0 & 3, 0 \\\cline{3-6}
  & $C$ & 3, \textbf{1} & \textbf{4}, 0 & 1, 0 & 2, 0 \\\cline{3-6}
  & $D$ & \colorbox{blue!25}{\textbf{4}, \textbf{2}} & 3, 0 & 2, 1 & 1, 1 \\\cline{3-6}
\end{tabular}
\end{table}
```
::: {.incremental}
  * Then any cell of the table in which all payoffs are marked to indicate a best response represents a NE.
  * Here, the two NEs are (D, a) and (A, d), which we could never have found from elimination.
:::
---

## Another Example: Nash Equilibrium in the Deer Hunt}
::: {.incremental}
  * We did already find the NEs of the Deer Hunt, but we had to go through and check all four strategy profiles. We can do it much faster by just using best responses:
:::
```{=latex}
\begin{table}[h]
\centering
\begin{tabular}{cc|c|c|}
  & \multicolumn{1}{c}{} & \multicolumn{2}{c}{Ogg}\\
  & \multicolumn{1}{c}{} & \multicolumn{1}{c}{$Deer$}  & \multicolumn{1}{c}{$Rabbit$} \\\cline{3-4}
  \multirow{2}*{Igg}  & $Deer$ & \colorbox{blue!25}{\textbf{2,2}} & 0,1 \\\cline{3-4}
  & $Rabbit$ & 1,0 & \colorbox{blue!25}{\textbf{1,1}} \\\cline{3-4}
\end{tabular}
\end{table}
```
---

## Another Example: When Elimination Does Nothing}
::: {.incremental}
  * This game has **absolutely no strategies** that can be eliminated: none are strictly dominated or non-rationalizable.
  * We can still find the NEs (of which there are quite a few) using best responses:
:::
```{=latex}
\begin{table}[h]
  \centering
  \begin{tabular}{cc|c|c|c|c|}
    & \multicolumn{1}{c}{} & \multicolumn{4}{c}{P$_2$}\\
    & \multicolumn{1}{c}{} & \multicolumn{1}{c}{$a$} & \multicolumn{1}{c}{$b$} & \multicolumn{1}{c}{$c$} & \multicolumn{1}{c}{$d$}  \\\cline{3-6}
    \multirow{5}*{P$_1$}  & $A$ & 1, 1 & 2, 2 & 2, 2 & 2, 1 \\\cline{3-6}
    & $B$ & 1, 3 & 1, 3 & 2, 2 & 2, 3 \\\cline{3-6}
    & $C$ & 1, 2 & 2, 4 & 1, 3 & 2, 3 \\\cline{3-6}
    & $D$ & 3, 2 & 2, 3 & 1, 4 & 2, 2 \\\cline{3-6}
  \end{tabular}
\end{table}
```
---

## iClicker Q4}
```{=latex}
\begin{table}[h]
\centering
\begin{tabular}{cc|c|c|c|}
  & \multicolumn{1}{c}{} & \multicolumn{3}{c}{P$_2$}\\
  & \multicolumn{1}{c}{} & \multicolumn{1}{c}{$X$} & \multicolumn{1}{c}{$Y$} & \multicolumn{1}{c}{$Z$} \\\cline{3-5}
  \multirow{3}*{P$_1$}  & $A$ & 3, 3 & 2, 2 & 1, 1 \\\cline{3-5}
  & $B$ & 4, 2 & 1, 1 & 2, 2 \\\cline{3-5}
  & $C$ & 1, 1 & 2, 2 & 3, 1  \\\cline{3-5}
\end{tabular}
\end{table}
```
::: {.incremental}
* In the game shown above, which of the following are the Nash Equilibria? (You will need to find best responses for both players.)
  1. (A, X)
  1. (A, Y)
  1. (B, X)
  1. (C, Z)
  1. More than one of the above.
:::
---

## Best Responses and Non-Rationalizability}
::: {.incremental}

* Finding best responses first makes it a lot easier to search for non-rationalizable strategies.

* Recall that a non-rationalizable strategy can also be called a non-best response: if none of the payoffs of a strategy are marked to indicate that it is a best-response, it is non-rationalizable. 

In other words

   * Any row in which none of Player 1's payoffs are marked to indicate a best response, is non-rationalizable.
   * Any column in which none of Player 2's payoffs are marked to indicate a best response, is non-rationalizable.
:::
---

## Example: Non-Rationalizability from Best Responses}
::: {.incremental}
* Finding best responses first makes it a lot easier to search for non-rationalizable strategies.
* Recall that a non-rationalizable strategy can also be called a non-best response: if none of the payoffs of a strategy are marked to indicate that it is a best-response, it is non-rationalizable. In other words:::: {.incremental}
  * Any row in which none of Player 1's payoffs are marked to indicate a best response, is non-rationalizable.
  * Any column in which none of Player 2's payoffs are marked to indicate a best response, is non-rationalizable.
:::
:::
---

## Example: Non-Rationalizability from Best Responses}
```{=latex}
\begin{table}[h]
  \centering
  \begin{tabular}{cc|c|c|c|c|}
    & \multicolumn{1}{c}{} & \multicolumn{4}{c}{P$_2$}\\
    & \multicolumn{1}{c}{} & \multicolumn{1}{c}{$a$} & \multicolumn{1}{c}{$b$} & \multicolumn{1}{c}{$c$} & \multicolumn{1}{c}{$d$} \\\cline{3-6}
    \multirow{4}*{P$_1$}  & $A$ & 1, 0 & 2, 1 & \textbf{3}, 1 & \textbf{4}, \textbf{2} \\\cline{3-6}
    & $B$ & 3, 1 & 2, \textbf{2} & 2, 0 & 3, 0 \\\cline{3-6}
    & $C$ & 3, \textbf{1} & \textbf{4}, 0 & 1, 0 & 2, 0 \\\cline{3-6}
    & $D$ & \textbf{4}, \textbf{2} & 3, 0 & 2, 1 & 1, 1 \\\cline{3-6}
  \end{tabular}
\end{table}
```
::: {.incremental}
  * We found these best responses earlier (as well as the NEs of this game): note that in the row for Player 1's strategy B, none of Player 1's strategies are marked.
  * Likewise, none of Player 2's payoffs are marked in column c. B and c are non-rationalizable strategies.
:::
---

## Example: Non-Rationalizability from Best Responses}
```{=latex}
\begin{table}[h]
  \centering
  \begin{tabular}{cc|c|c|c|c|}
    & \multicolumn{1}{c}{} & \multicolumn{4}{c}{P$_2$}\\
    & \multicolumn{1}{c}{} & \multicolumn{1}{c}{$a$} & \multicolumn{1}{c}{$b$} & \multicolumn{1}{c}{$c$} & \multicolumn{1}{c}{$d$} \\\cline{3-6}
    \multirow{4}*{P$_1$}  & $A$ & 1, 0 & 2, 1 & \textbf{3}, 1 & \textbf{4}, \textbf{2} \\\cline{3-6}
    & $B$ & 3, 1 & 2, \textbf{2} & 2, 0 & 3, 0 \\\cline{3-6}
    & $C$ & 3, \textbf{1} & \textbf{4}, 0 & 1, 0 & 2, 0 \\\cline{3-6}
    & $D$ & \textbf{4}, \textbf{2} & 3, 0 & 2, 1 & 1, 1 \\\cline{3-6}
  \end{tabular}
\end{table}
```
::: {.incremental}
  * Performing IENBR reveals additional non-rationalizable strategies:
    * Once we eliminate B, b becomes non-rationalizable.
    * Once we eliminate b, C becomes non-rationalizable.
:::
---



## Classifying NEs}
::: {.incremental}
  * Nash Equilibria may be either \underline{strict} or \underline{weak}.
  * A Nash Equilibrium is strict if and only if each player would receive a smaller payoff by changing their own strategy.
  * If a Nash Equilibrium is not strict---meaning that at least one player could change their own strategy and receive an equal (but not larger) payoff---it is weak.
:::
---

## Intuition on Strict vs. Weak Equilibria}
::: {.incremental}
* In any Nash Equilibrium, no player has a reason to change their own strategy---they cannot get a higher payoff this way.
* Strict Nash Equilibria go a little further: not only does no player have a reason to change their own strategy, they also have a reason **not** to, because any other strategy would provide them a worse payoff.
* If a Nash Equilibrium is weak, it means that some player could change their strategy, and get exactly the same payoff they already were. They have no reason to do this, but also no reason **not** to.
* We can also say that a strict Nash Equilibrium is one where each player is playing a strategy which is a **unique** best response to the strategies chosen by other players.
:::
---

## Deer Hunt: Strict Nash Equilibria}
```{=latex}
\begin{table}[h]
\centering
\begin{tabular}{cc|c|c|}
& \multicolumn{1}{c}{} & \multicolumn{2}{c}{Ogg}\\
& \multicolumn{1}{c}{} & \multicolumn{1}{c}{$Deer$}  & \multicolumn{1}{c}{$Rabbit$} \\\cline{3-4}
\multirow{2}*{Igg}  & $Deer$ & $\underline{2},\underline{2}$ & $0,1$ \\\cline{3-4}
& $Rabbit$ & $1,0$ & $\underline{1},\underline{1}$ \\\cline{3-4}
\end{tabular}
\end{table}
```
::: {.incremental}
* Here, note that at each Nash Equilibrium, each player has no other strategy providing the same payoff. This is a strict Nash Equilibrium.
:::
---

## Not Quite the Trolley Problem: Weak Nash Equilibria}
```{=latex}
\begin{table}[h]
\centering
\begin{tabular}{cc|c|c|}
& \multicolumn{1}{c}{} & \multicolumn{2}{c}{Michael}\\
& \multicolumn{1}{c}{} & \multicolumn{1}{c}{$Swerve$}  & \multicolumn{1}{c}{$Straight$} \\\cline{3-4}
\multirow{2}*{Eleanor}  & $Swerve$ & $\underline{1}, \underline{1}$ & $\underline{1}, \underline{1}$ \\\cline{3-4}
& $Straight$ & $\underline{1}, \underline{1}$ & $0, 0$ \\\cline{3-4}
\end{tabular}
\end{table}
```
::: {.incremental}
* However, in this game, each Nash Equilibrium features at least one player who could still get the same payoff if they change their strategy.
:::
---

## Classifying Games Based on NEs}
::: {.incremental}
  * Now that we've talked about several ways to find a game's NEs, we can start to talk about classifying games using them.
:::
---

## Prisoners' Dilemmas}
```{=latex}
\begin{table}[h]
  \centering
  \begin{tabular}{cc|c|c|}
    & \multicolumn{1}{c}{} & \multicolumn{2}{c}{Luca}\\
    & \multicolumn{1}{c}{} & \multicolumn{1}{c}{$Testify$}  & \multicolumn{1}{c}{$Keep~Quiet$} \\\cline{3-4}
    \multirow{2}*{Guido}  & $Testify$ & $-10,-10$ & $0,-20$ \\\cline{3-4}
    & $Keep~Quiet$ & $-20,0$ & $-1,-1$ \\\cline{3-4}
  \end{tabular}
\end{table}
```
::: {.incremental}
* So far, I've only used the payoffs above to describe the Prisoner's Dilemma.
* But we can change those payoffs---we can also change the story behind the game, and the names of the players and strategies, and it would still count as a Prisoner's Dilemma.

In general, a Prisoner's Dilemma is any game in which:

  * The players have the same strategies, A and B.
  * A strictly dominates B, making (A, A) the only NE.
  * But (B, B) is better for both players than (A, A).
:::
---

## Other Representations of the Prisoners' Dilemmas}
```{=latex}
\begin{table}[h]
  \centering
  \begin{tabular}{cc|c|c|}
    & \multicolumn{1}{c}{} & \multicolumn{2}{c}{Luca}\\
    & \multicolumn{1}{c}{} & \multicolumn{1}{c}{$Testify$}  & \multicolumn{1}{c}{$Keep~Quiet$} \\\cline{3-4}
    \multirow{2}*{Guido}  & $Testify$ & $1, 1$ & $3, 0$ \\\cline{3-4}
    & $Keep~Quiet$ & $0, 3$ & $2, 2$ \\\cline{3-4}
  \end{tabular}
\end{table}
```
```{=latex}
\begin{table}[h]
  \centering
  \begin{tabular}{cc|c|c|}
    & \multicolumn{1}{c}{} & \multicolumn{2}{c}{$P_2$}\\
    & \multicolumn{1}{c}{} & \multicolumn{1}{c}{$A$}  & \multicolumn{1}{c}{$B$} \\\cline{3-4}
    \multirow{2}*{$P_1$}  & $A$ & $0, 4$ & $2, 3$ \\\cline{3-4}
    & $B$ & $-1, 6$ & $1, 5$ \\\cline{3-4}
  \end{tabular}
\end{table}
```
---

## Coordination Games}
::: {.incremental}
  * A [coordination game]{.hi} is a game in which the players all have the same strategy sets, and the NEs are all of the strategy profiles where the players choose the same strategy.
  * The Deer Hunt is a coordination game.
:::
```{=latex}
\begin{table}[h]
\centering
\begin{tabular}{cc|c|c|}
  & \multicolumn{1}{c}{} & \multicolumn{2}{c}{Ogg}\\
  & \multicolumn{1}{c}{} & \multicolumn{1}{c}{$Deer$}  & \multicolumn{1}{c}{$Rabbit$} \\\cline{3-4}
  \multirow{2}*{Igg}  & $Deer$ & \colorbox{blue!25}{\textbf{2,2}} & 0,1 \\\cline{3-4}
  & $Rabbit$ & 1,0 & \colorbox{blue!25}{\textbf{1,1}} \\\cline{3-4}
\end{tabular}
\end{table}
```
---

## Other Coordination Games}
```{=latex}
\begin{table}[h]
  \caption*{Bach or Stravinsky?}
  \centering
  \begin{tabular}{cc|c|c|}
    & \multicolumn{1}{c}{} & \multicolumn{2}{c}{Stravinsky Fan}\\
    & \multicolumn{1}{c}{} & \multicolumn{1}{c}{Bach}  & \multicolumn{1}{c}{Strav.} \\\cline{3-4}
    \multirow{2}*{Bach Fan}  & Bach & \colorbox{blue!25}{\textbf{3, 2}} & 0,0 \\\cline{3-4}
    & Strav. & 0,0 & \colorbox{blue!25}{\textbf{2, 3}} \\\cline{3-4}
  \end{tabular}
\end{table}
```
```{=latex}
\begin{table}[h]
  \centering
  \begin{tabular}{cc|c|c|c|}
    & \multicolumn{1}{c}{} & \multicolumn{3}{c}{$P_2$}\\
    & \multicolumn{1}{c}{} & \multicolumn{1}{c}{A}  & \multicolumn{1}{c}{B}  & \multicolumn{1}{c}{C} \\\cline{3-5}
    \multirow{2}*{$P_1$}  & A & \colorbox{blue!25}{\textbf{1, 1}} & 1, 0 & 3, 0 \\\cline{3-5}
    & B & 0, 1 & \colorbox{blue!25}{\textbf{2, 2}} & 2, 1 \\\cline{3-5}
    & B & 0, 3 & 1, 2 & \colorbox{blue!25}{\textbf{4, 4}} \\\cline{3-5}
  \end{tabular}
\end{table}
```
---


## Anti-Coordination Games}
::: {.incremental}
  * An [anti-coordination game]{.hi} is a game in which the players all have the same strategy sets, but the NEs are all of the strategy profiles where the players choose different strategies.
:::
```{=latex}
\begin{table}[h]
  \caption*{Chicken}
  \centering
  \begin{tabular}{cc|c|c|}
    & \multicolumn{1}{c}{} & \multicolumn{2}{c}{Buzz}\\
    & \multicolumn{1}{c}{} & \multicolumn{1}{c}{Straight}  & \multicolumn{1}{c}{Swerve} \\\cline{3-4}
    \multirow{2}*{Jim}  & Straight & -10, -10 & \colorbox{blue!25}{\textbf{5, -1}} \\\cline{3-4}
    & Swerve & \colorbox{blue!25}{\textbf{-1, 5}} & 0, 0 \\\cline{3-4}
  \end{tabular}
\end{table}
```
---

## Symmetric Games}
::: {.incremental}
  * A [symmetric game]{.hi} is a game which is **indifferent to an exchange of players** in other words, a game where the players are interchangeable.
  * Consider the Prisoner's Dilemma: if we swap the players' names, and their positions in the game table, and the order of their payoffs, we get the same game that we started with.
  * A two-player game with a game table is symmetric if:
    * The players have the same strategy sets.
    * In the on-diagonal cells of the game table, the players receive equal payoffs.
    * In the "mirrored" off-diagonal cells of the game table, the players' payoffs are reversed.
  * Of the games we've just looked at, the Deer Hunt, the 3x3 coordination game, and Chicken are symmetric games. Bach and Stravinsky is not.
:::
---

