---
title: "Exam Materials"
---

# Exam Policies:

You will have 80 minutes to complete 10 multiple choice and 3-4 short-answer questions.

<u>Allowed Materials</u>:

  * 3x5 inch handwritten notecard
  * scientific non-programmable graphing calculator (optional)

# Midterm

[Midterms Topics](midterm-topics.qmd)

## Practice Midterm [🗌 Download](PracticeExam/Midterm/PracticeMT_F25.pdf){.btn .btn-outline-primary .btn role="button"}
```{=html}
<details>
  <summary>Answer Key</summary>
  <div class="embed-container">
    <iframe src="PracticeExam/Midterm/PracticeMT_F25_key.pdf" style="border: 0.5px" height="1000" width="800"></iframe>
  </div>
</details>
```

## Fall 2025 Midterm 

| Version 1 | Version 2 |
|:---------:|:---------:|
| [📕V1 (blank)](Midterm/EC327F25_mt_v1.pdf){.btn .btn-outline-primary .btn role="button"} | [📗V2 (blank)](Midterm/EC327F25_mt_v2.pdf){.btn .btn-outline-primary .btn role="button"} |
| [📕V1 Answer Key](Midterm/EC327F25_mt_v1_key.pdf){.btn .btn-outline-primary .btn role="button"} | [📗V2 Answer Key](Midterm/EC327F25_mt_v2_key.pdf){.btn .btn-outline-primary .btn role="button"} |

[📊 Performance Report](report.qmd){.btn .btn-outline-primary .btn role="button"}

---

# Final

## Practice Final [🗌 Download](PracticeExam/Final/PracticeFinal_clean.pdf){.btn .btn-outline-primary .btn role="button"}
```{=html}
<details>
  <summary>Answer Key</summary>
  <div class="embed-container">
    <iframe src="PracticeExam/Final/PracticeFinal_key.pdf" style="border: 0.5px" height="1000" width="800"></iframe>
  </div>
</details>
```