---
title: Syllabus
---

[Complete Fall 2025 syllabus (pdf)](main.pdf){.btn .btn-outline-primary .btn role="button"}

## Course Description

This course introduces the field of game theory, which involves the analysis of strategic situations;
where the consequences one person's choice depend on the actions of others.
The examples of settings we may discuss range from simple games like rock, paper, scissors; 
to more complicated games of incomplete information in the market for used cars. 

We will introduce the general concept of equilibrium and explore the different forms of equilbria 
in different settings.
Students will learn through in-person lectures and discussions,
and build their own skills through participation in in-class activities.

This elective is suitable for economics majors and anyone interested in understanding the strategic dynamics that shape our decisions.

## Course Details

### Course Pages:

  * [**Canvas**](https://canvas.uoregon.edu/courses/274671):
  The class Canvas page will be where you submit graded assignments and where you can check your current grade.

  * [**Course Website**](https://danteyasui.org/EC327/)

  This website will be kept up to date with the current class schedule, activities, assignments, and slides.

### Prerequisites:

One of EC101 or EC201.

The most important prerequisite skills you will need for this class are mainly college-level algebra
and working with simple systems of equations.
If it has been a while since your last math class, 
it may be helpful to review concepts like linear equations, graphing of equations, and factoring quadratics
(for example units 1-5 of the [Khan Academy course](https://www.khanacademy.org/math/college-algebra)).

### Objectives:

This course aims to help you to understand the fundamental principles of game theory, become familiar with basic classes of games, practice the mathematical skills to solve for the appropriate equilibria, apply game theoretic models to real-world interactions, and recognize limitations and critiques of the theory.

### Textbook:

  * *Games of Strategy* by Avinash Dixit, Susan Skeath, and David McAdams, **5th edition**.

  The most recent edition of the E-book is available from the [publisher](https://wwnorton.com/books/Games-of-Strategy).
  If you have an older or newer edition of this book, please make sure that the chapters align with the topics on the class schedule.

Any other readings I assign (for example articles, news stories, etc.) will be posted on the course website.

### Attendance:

This is an in-person class that will meet at the times specified in the UO Class Schedule.
Regular attendance and active participation is expected.
You will demonstrate your attendence by participating in regular in-class activities and group discussions.

If you are unable to attend class for any reason,
you are responsible for keeping track of whatever activites, discussions, and lecture material we cover in your absence.
Please ask your classmates and check the website to see what you may have missed.
If you miss more than two or three classes in the term, you should meet with the instructor to see what options are best for you to meet the class expectations.
 
### Office Hours:

There will be two in-person office hour sections each week 
during which you will have the opportunity to meet with the instructor to ask for further clarification on class concepts,
homework assignments, etc.
These times are most effective if you come prepared with specific questions or topics that you want to discuss.
Because my office space is limited, unless otherwise stated, office hours will be held in the [Tykeson 352](https://map.uoregon.edu/aeddb7eca),
on the third floor next to the blackboards.
As office hour times are subject to change, please check the Canvas page for the most up to date schedule.

If you are unable to attend the scheduled office hour times, I am also available to meet by appointment.

## Grading Policies:

| Category | Grade |
|---------|--------|
|Activities/Discussions | 10% |
|Quizzes | 10% |
|Homework | 20% |
|Midterm Exam | 30% |
|Final Exam | 30% |

### Activities/Discussions

This class uses interactive learning in the form of in-class discussion and group activities.
Your Activities grade will be determinded by your participation (i.e., were you present, respectful, and engaged)
as well as a short written report which you will submit to canvas.
Depending on what we do in class, the report will outline the discussion you had with your classmates
and/or record the data from the game you played.

If you are unable to attend class when we have an activity, you may make up for your lost participation by designing an alternative activity which you can complete on your own time in consultation with the instructor.
Only up to 2 missed activities may be substituted for per quarter.

### Quizzes

There will also be a number of quizzes posted on Canvas which are mostly designed to keep you up to date with the reading.
There will be one quiz for each assigned chapter and they will be due on the Friday of the week we cover that chapter in class.
Your lowest quiz score will be dropped.
 
### Homework

To help practice your understanding of the material, you will complete a written homework assignment covering the corresponding chapter every week.
You will post your submissions as *a single pdf file* including all work.
Answer keys will be automatically posted on the due date in Canvas, so no late submissions will be accepted.
However, your lowest grade will be dropped at the end of the term.

Your submissions will be graded not only on how well they match the rubric,
but also on how clearly your submission demonstrates your understanding of the material.

### AI use policy

For this class, you may find it helpful to use `artificial intelligence' (AI) software tools like ChatGPT to brainstorm, create outlines, or summarize readings.
However, any written content you submit for homework \textit{must be in your own words} and demonstrate your own understanding of the material.

If you use any AI generated content to help you write your submission, your submission must also provide the following:

  * **AI Tool Details:** What specific model, version, website provider did you use?
  * **Prompt:** State the specific prompts you used when generating text, images, etc. 
  * **Alignment:** Describe what steps you took or how you edited the generated content to align with the rubric guidelines.
        This may include refining prompts, cross-referencing with lecture notes, or seeking clarification for ambiguous responses.
  * **Demonstrate Comprehension:** Along with your answer, briefly evaluate how useful the AI tool was for your submission by highlighting what it got right and what you needed to correct.

### Exams:

Exams will be in-person and closed-note.

There will be one midterm exam on week 5 and one final exam administered at the time specified in the Registrar’s final exam schedule.
Each exam will have a multiple-choice section (based on quiz questions) and some long-answer questions (based on homework).
You are allowed to bring a 3x5 inch handwritten notecard (front and back sides).

If you cannot attend the midterm due to extreme circumstances, you may choose to move the weight that would have been applied to the midterm score to your final exam instead.
To qualify for re-weighting, a request must be submitted to the instructor no later than two days after the midterm.
