## Syllabus Document


:::{incremental}
  - Most up to date version on github
  - I will also upload to Canvas
  - print, sign, and upload as your first assignment
:::

# Class Expectations

## Prerequisites
 * **Courses:** EC201 *or* EC202

 * **Knowledge:** This class will require you to use some simple algebra and graphing skills. If you felt uncomfortable with the level of math in EC201, I recommend that you review how to solve simple systems of equations, inequalities, and fractions.
   - There are great free resources out there like [Khan Academy](https://www.khanacademy.org/math/algebra), but always feel free to reach out for help or other suggestions.
---

## Student Expectations
::: {.incremental}
  * [Come to class]{.hii}
    - Pay attention to lectures, take notes, review topics at home
    - Participate in group work & activities
    - [Ask questions!]{.hi}
  * [Read the textbook]{.hii}
  * [Communicate respectfully]{.hii}
    - With your classmates
    - With me & grader
  * [Have academic integrity]{.hii} ^[see UO's [Student Conduct Code](https://teaching.uoregon.edu/resources/academic-integrity-uo)]
    - Verify that all submitted work is your own
    - Provide sources for *all* information that you found outside this class
:::

---

## Instructor Expectations
  * [Provide course material]{.h}
    - Slides will be updated on github
    - I will also try to post them on Canvas, but not as regularly
    - Assignments posted on Canvas w/ due dates, submission entry
  * [Face-to-face Interaction]{.h}
    - [Classes]{.hi}
      + Ask me to clarify if something doesn't make sense
      + Ask me to slow down if I'm going too fast
    - [Office Hours]{.hi}
      + Use them!!

# Admin Stuff

## Problem Sets
You will practice what we learn in class on independently.

Each homework assignment will include a few problems that will be similar to what you will see on exams.

::: {.incremental}
  * Learning something new takes practice, so these are designed to help you
  keep up with the concepts

  * You will be graded not only on whether you got a certain answer,
  but also more importantly on *how you communicate your understanding*

    - See Canvas rubric for more info
:::

---

## Class Activities

::: {.incremental}
  * Sometimes I will ask you to play the types of games we discuss in lectures
    - Record the strategies you chose and the outcomes
    - Reflect on how you played the game
    - Relate it to lecture concepts
:::

::: notes
  * I'm still working out how best to implement
  * this is how you participate, records attendance on activity days
  * hopefully lets you experience first-hand the things we learn
:::
---

## Exams

You will demonstrate how well you understand concepts individually on a [midterm]{.hi}
and a [final]{.hi} exam

:::{.incremental}
  * [Midterm]{.hi}
    + sometime around week 5 (Oct. 28th or 30th)
    + Will test you on definitions, solution concepts, and apply them to critical thinking problems

  * [Final]{.hi}
    + finals week of December 9 (check duckweb for specific date)
    + Covers everything we learned in the quarter, with more focus on concepts from the 2nd half
:::

::: notes
  * Dept policy is 65% As & Bs
  * expect exams to be difficult
  * Best way to prepare is lots of practice
:::

---

## Grading

:::: {.columns}

::: {.column width="40%"}
[Problem Sets]{.hi}

[In-class Activities]{.hi}

[Midterm]{.hi}

[Final]{.hi}
:::

::: {.column width="40%"}
30%

10%

30%

30%
:::

::::

---

### Policies

:::{.incremental}
  * [No make-up exams!]{.h}
    - if you absolutely cannot attend midterm, you can add its weight to final exam
  * Problem set keys posted automatically after deadline
    - -> no late submissions accepted
:::

---

## Campus Resources

  * [Accessible Education Center]{.hi}
    - [aec.uoregon.edu](https://aec.uoregon.edu/)

  * [Support for vicitms of assault, harassment, stalking]{.hi}
    - [safe.uoregon.edu](https://safe.uoregon.edu/)
    - 24/7 hotline: (+1) 541-346-SAFE (7244)

  * [Health and Wellbeing]{.hi}
    - [University Counseling Services](https://counseling.uoregon.edu)
    - [Basic Needs Program](https://basicneeds.uoregon.edu/)

  * [Religious Observance Accomadations]{.hi}
    - [Provost website](https://provost.uoregon.edu/religious-observance-accommodations-policy)

::: aside
These resources and others are also included in the course syllabus
:::

::: notes
  * I am here to support you, but not trained or equipped for emergencies
  * I will not ask for reasons you cannot attend class or exams
  * I am not a mandated reporter: will only pass on info if you request
:::

---

## Course Pages

[https://canvas.uoregon.edu/courses/251353](https://canvas.uoregon.edu/courses/233504)
  - submit your assignments
  - check deadlines

[github.com/dyasui/EC327](https://github.com/dyasui/EC327)
  - Find up-to-date versions of slides/assignments
  - *let me know if links are broken*

