
# What is a Game? Definitions

## What do all these questions have in common?
::: {.incremental}
  * They all involve people making choices which depend on the choices of others
  * In other words, they are questions of [strategy]{.hi}:

    > **Strategic interdependence** is present in a social situation when what is best for someone *depends* on what someone else does. ^[*Harrington*, pg. 2]
:::

---

## *Strategic* Choice vs. other types of choices

::: {.incremental}

  * Economics is the study of [constrained choice]{.hi};
  in EC311, we introduce the *utility maximization problem* as the workhorse model
  
    - These types of problems usually only involve one agent;
    the consumer, who is only constrained by their budget
    
  * We use the term [*strategic games*]{.hi} to distinguish from these single-agent optimization problems 
  
A [*game*]{.hi} is a type of problem featuring multiple agents, called [players]{.hi},
  
  * in which their optimal choice [depends on the optimal choices of  other players]{.hii}.
  
:::

---

## A definition of a game ^[adapted from [Leigh Tesfatsion](https://www2.econ.iastate.edu/tesfatsi/)'s slides]

A **Game** consists of:

::: {.incremental}

  * a collection of decision-makers, called [players]{.hi};

  * the set of [information]{.hi} available to each player;

  * the [strategies]{.hi} available to each player in each information state;

  * a mapping from the intersection strategies of all players to outcomes;

  * [preferences]{.hi} of the individual players over all possible outcomes

:::

# Who are the players?

## What defines a player?

 * [Preferences]{.h}: 

::: {.incremental}

  - In economics, we say people have *unlimited* wants and *limited*
  needs

  - Therefore, we have to think about how people *prioritize* what
  they want more

:::

 * [Beliefs]{.h}:

---

## What defines a player?

  * [Preferences]{.h}: 

  * [Beliefs]{.h}:

::: {.incremental}

  - My beliefs about the world define how I act

  - If I am exposed to new *information* it can potentially change my
  beliefs, and therefore change my actions 

  - Information and beliefs of players will define later game theory
  topics

:::

---

## Preferences

[Preferences]{.h} describe the subjective ranking that we put on different alternatives.

For example, on the set of Eugene boba stores, my preference ranking goes like this;

::: {.incremental}
  1. [Tea 4](https://maps.app.goo.gl/zCVTUnaaYLD1Rwaw6) - major chain, good quality and selection
  2. [Day & Night](https://www.daynightboba.com/) - they have mango sago, cute location
  3. [Bobahead]() - no more campus location ðŸ˜”
  4. No boba
  5. [Rabbit Hole](http://therabbitholeteabar.com/) - no hate, just not for me
:::

---

## Rational Preferences

The [rational model]{.h} of choice is the foundation of all economics.

Its assumptions are that:

::: {.incremental}

  * People have [complete preferences]{.h}
    - for *every* pair of options, you can either tell me which you prefer or that you are *indifferent*
    - for any pair of deserts, $\{ \ ðŸ¨ \ , \ ðŸ© \ \}$, either $(ðŸ¨ \succ ðŸ© \ )$, or $(ðŸ© \ \succ ðŸ¨ \ )$, or $(ðŸ¨ \sim ðŸ© \ )$

  * Preferences are [transitive]{.h}
    - if $(â˜• \succ ðŸµ \ )$ and $(ðŸµ \succ ðŸ¶ \ )$, then $(â˜• \succ ðŸ¶)$  ( for any $\{â˜• \ , ðŸµ \ , ðŸ¶ \ \} \in ðŸ«– \ $)
:::

---

## Rationality

One key proposition of rationality is that we can represent preferences by real numbers.

::: {.incremental}

A [utility function]{.h} maps a choice to a single number.

For example, let $u(.)$ be the utility function from emoji to utils

  * I can have $u(ðŸº) =5$,
  $u(ðŸŒ¯)=10$,
  $u(ðŸ¤¸)=25$

  * I can also have $u(ðŸº \ , ðŸŒ¯) = 20$, $u(ðŸº \ , ðŸŒ¯ \ , ðŸ¤¸) = 15$

:::
  
---
  
## Ordinal vs. Cardinal numbers

::: {.incremental}

  * [Cardinal:]{.h} amounts which can be measured in meaningful units are *cardinal numbers* 
    
    + examples: $9.99, 80 students, 50:50 odds

  * [Ordinal:]{.h} all that matters is the *relative ranking*
  
    + examples: utility; what does 100 utility mean? (it's less than 200)
  
:::

---

## Don't worry!

::: {.incremental}

  * For this class, you won't need to worry about utility functions 
  (if you want to, take EC311).
  
  * I will almost always give you specific values of utility which we will call [payoffs]{.hi}.
  
:::

---

## Payoffs

What is a player's goal in a game?

> To maximize their expected [payoff]{.h}

::: {.incremental}

  - A payoff can represent many things which come with a specific outcome

  - Whenever you see a payoff, assume that it represents everything about 
  that outcome which an agent cares about

  - For example, your payoff to giving to charity would include 
  the emotional benefit you feel towards giving to others

:::

---

## Payoffs

What is true of payoffs?

> Higher numbers are more preferred

> They are [Ordinal]{.hi}; i.e., the relative units don't matter
^[except when we talk about *expected* payoffs later]

> They capture *everything* in a game that a player cares about

---

## Payoffs
::: {.incremental}
  * Sometimes my enjoyment of a thing depends on the *state* of the world

| My choice   | My friends' choice | My payoff  |
|-------------|--------------------|------------|
| Duck's game |     Duck's game    |     3      |
| Duck's game |      Stay home     |     2      |
|  Stay home  |     Duck's game    |     1      |
| Stay home   |      Stay home     |     2      |

: socially-dependent preferences {.striped .hover}

  * Is this an example of a [strategic]{.hi} or [non-strategic]{.hi} choice?
:::

---

### *Expected* Payoffs

Often games involve some amount of *chance*;
with random probabilities of each outcome happening

  * We need tools for thinking about how people think about [risk]{.hi}

---

### *Expected* Payoffs

> In math, an [expected value]{.hii}
> is the average value of a *random variable*,
> weighted by the probability of each value occuring

---

## *Expected* Payoffs

For example, suppose $X$ is a random variable which is equal to: 

  * [1]{.hii} with [50%]{.hi} probability,
  * [2]{.hii} with [25%]{.hi} probability,
  * [3]{.hii} with [25%]{.hi} probability

What is the *expected value* of $X$? ($E(X)$)

. . .

$$
\begin{align}
E(X) & = .5 (1) + .25 (2) + .25 (3) \\
 & = .5 + .5 + .75 = 2.75
\end{align}
$$

---

### *Expected* Payoffs

An [Expected Payoff]{.hi} is just the *expected value* of possible payoffs

> An average of the payoffs associated with every possible outcome,
> weighted by the corresponding probability of each outcome happening

---

### *Expected* Payoffs

Consider the following choice:

::: {.callout-note icon=false}
## Option A:
I flip two coins; 
  - if both land **heads**, you win $100
  - otherwise you get $0
:::

::: {.callout-note icon=false}
## Option B:
You just get $25 for sure
:::

---

### *Expected Payoffs*

  * If you choose [Option A]{.h}, we call you [risk averse]{.hii}

  * If you choose [Option B]{.h}, you are [risk loving]{.hii}

  * If you are *indifferent* between the two options, 
  you would be [risk neutral]{.hii}


All of these difference preferences can be incorporated in the *rational* 
model with the right *utility function*

---

## Beliefs

Our theories will have to make assumptions about what players **know**.

All of our games will at least assume that [all players know all of the rules]{.h}.

---

## Beliefs

We will assume that all players know^[and believe]:

::: {.incremental}
  - Who else is playing,

  - all of the strategies each player could *potentially* choose,

  - everyone's payoffs for all possible combinations of strategies by all players,

  - and that everyone else is maximizing their payoffs
:::

