---
name: theory
---

## Theory in a data-driven world? ^[adapted from Glen Waddell's microeconometrics class]
  > "The theory of economics does not furnish a body of settled conclusions
immediately applicable to policy. It is a method rather than a doctrine, an
apparatus of the mind, a technique of thinking which helps its possessor to draw
correct conclusions." — Keynes

## Why is theory useful?
::: {.incremental}
[helps us simplify and understand complex systems]{.hi}

  - Social systems are really hard, game theory helps us focus on small parts at a time

[lets us generate *falsifiable* & *testable* hypotheses]{.hi}

  - Good econometrics is informed by good theory

[gives us common ground to analyze important questions]{.hi}

  - I often see debates devolve into people arguing on differences of definitions.
  - How can we focus on the details that really matter?
:::
---

### Why all the math?
::: {.incremental}
I've heard this frustration before from students in econ elective classes (especially 327).

I want this class to include activities that are more interactive, but math will still be present.
:::
---

### My own experience with learning to love math

::: {.notes}
  * Throughout grade school, I hated taking classes that just required me to memorize definitions and do tedious problems that weren't related to anything I was interested in.

  * I liked reading and writing, but taking journalism classes and going a liberal arts college made me realise that just because your arguments sound nice doesn't always make them thoughtful or useful.

  * It wasn't until I took a college game theory class taught by an econ professor that I started to apprecieate what economics has to offer.

  *
:::
---