---
name: SurvivorFlags
---

## Activity 2: Survivor 21 Flags Challenge

{{< video https://youtu.be/aonCsvi0LKc width="800" height="600" >}}

https://youtu.be/aonCsvi0LKc

---

## Split Into Groups

```{r}
#| warning: false
#| echo: false
library(tidyverse)

names <- read_csv("EC327names.csv") %>% select(First, Last) %>%
  # combine first and last names
  unite(name, c(First, Last), sep = " ", remove = TRUE) %>%
  # shorten last names to initial
  mutate(name = sub("(\\w+)\\s(\\w)\\w+", "\\1 \\2.", name))

n = nrow(names)
group_size = 3
num_groups = round(n/group_size)

# set seed to make group selection consistent across sessions
set.seed(2024)
# assign groups and make a table
names %>%
  mutate(
         row_number = row_number(),
         Group = sample(rep_len(1:num_groups, n), n, replace = FALSE)
         ) %>%
  arrange(Group, row_number) %>%  # Sort by group and then row number
  select(-row_number) %>%  # Remove temporary row_number column
  group_by(Group) %>%
  mutate(row = row_number()) %>%
  pivot_wider(names_from = Group, values_from = name, names_prefix = "Group") %>%
  ungroup() %>%
  select(-row) %>%
  knitr::kable()

```

---

## Set Up

::: {.incremental}
  
  * Find an opposing group
  
  * Pick someone to record flags for each round
  
  * Draw 21 flags on whiteboard
  
  * Discuss strategy w/ your group for 1 minute
  
  * Play the game!
  
    + Don't forget to record how many flags each round!!!
  
:::
  
---

## Record your Data!

[Google Sheet](https://docs.google.com/spreadsheets/d/13rOHLWJa--0BuvfI83pGdGWFFANsx1gNkx3TJl3A8ek/edit?usp=sharing)

  * Check the first sheet for an example of how to record your data

  * Find a free sheet at the bottom of the page

  * Ask me if something doesn't make sense!

---

## Modified Rules: choose number of flags to start

Find a new team to play against (losers move)

::: {.incremental}

  * This time, one team will choose the number of starting flags: between 15-25
  
  * The other team will choose whether to allow max. of 2-5 flags per round
  
  * Play and record! 
  
:::

---

## Discuss 

In your teams briefly discuss the following:
  
  * Is there a correct way to play the game?
  
  * How did you find out the best way to play the game?
  
  * Is the game solved meaning that the winner can be correctly predicted from any point in the game? If so, should the first or second team always win?
  
  * Were there more errors in the first games played than the last games played? Why?
  
  * How was this game different from the guessing 2/3rds game?
  
---

## Solution:

{{< video https://youtu.be/K_MckZc8VvQ width="1000" height="600" >}}

https://youtu.be/K_MckZc8VvQ

---

## Group Exercise:

Consider the Flag game but instead of starting with 21 flags the game starts with 5
flags, and instead of being able to pick 1,2, or 3 flags teams can only pick 1 or 2
flags.

1. _Draw the extensive form game tree complete with all payoff for both teams._

2. _How many total strategies are there for team 1?_

3. _Use pruning to eliminate actions to get to a rollback equilibrium. Who will win? What is the winning strategy?_

---

## Recap

  * There *is* a correct way to play: we will later call the *Nash equilibrium*
  
  * You likely used some form of *backwards induction* or *rollback* reasoning
  
  * This game was *sequential* unlike the *simultaneous* 2/3rds game

